spring.application.name=demo

# Server Port (8080 busy aslyamule 8082 kela aahe)
server.port=0

# MySQL Configuration (Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/exam_system
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Redis Configuration (Docker)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis